#!/bin/ksh 
# #######################################################
# Bias Correct AIGEFS 
# #######################################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################

set -xa

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-aigefs}
export RUN=${RUN:-aigefs}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATAROOT: Location of working directory, default to /lfs/f1/ops/${envir}/tmp
# SENDECF: If the job is to be running using SMS, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
#####################################################################################

export PS4='${PMI_FORK_RANK}: $SECONDS + '
# JY export PS4='${PMI_FORK_RANK}: $SECONDS `basename $0` + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
#export DATAROOT=${DATAROOT:-/lfs/f1/ops/${envir}/tmp}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}

mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
#export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################

export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

################################################################
# SENDCOM=YES--Copy output file to ${COMROOT}
# SENDECF=YES--Allow to talk back to SMS
# SENDDBN=YES--Alert output file to TOC, set to NO for testing
################################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}          # need to set to NO for testing
export SENDECF=${SENDECF:-YES}

####################################
# Specify Execution Areas
####################################
 
export HOMEaigefs=${HOMEaigefs:-${PACKAGEROOT}/aigefs.${aigefs_ver}}
export EXECaigefs=${EXECaigefs:-$HOMEaigefs/exec}
export FIXaigefs=${FIXaigefs:-$HOMEaigefs/fix}
export USHaigefs=${USHaigefs:-$HOMEaigefs/ush}

#export ERRSCRIPT=err_chk
#export LOGSCRIPT=startmsg
#export REDOUT='1>>'
#export REDERR='2>'

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. ./PDY

##############################################
# Define COM directories
##############################################

#CMD - COMIN will need to be fixed when aigefs_forecast com structure is updated
export COMIN=${COMIN:-$(compath.py ${envir}/$NET/$aigefs_ver)}/$RUN.$PDY/$cyc
export COMOUT=${COMOUT:-$(compath.py -o $NET/$aigefs_ver/$RUN.$PDY)}/${cyc}/products/ensstat

mkdir -m 775 -p ${COMOUT}

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#####################
# Execute the scripts
#####################

#####################################
#  calculate ensemble mean and spread
#####################################

export DATAHOLD=$DATA

export DATA=$DATAHOLD/dir_avgspr
mkdir -p $DATA
cd $DATA
$USHaigefs/aigefsens_avgspr.sh                  

cat $DATAHOLD/dir_avgspr_bc/$pgmout.360_avgspr
cat $DATAHOLD/dir_avgspr/$pgmout.360_avgspr

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [ $KEEPDATA != YES ]; then
  cd $DATAROOT
  rm -rf $DATA
  rm -rf $DATAHOLD
fi

date
